name: Publish via GitHub Pages

on:
  push:
    branches: ["**"]

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install pre-commit
        run: |
          pip install pre-commit

      - name: Run pre-commit checks
        run: |
          pre-commit run --all-files

      - name: Build mkdocs
        run: |
          mkdocs build
